### ISSUE TITLE
plugin stops- unable to connect

### ISSUE THREAD

**Issue by agrieco** [james-fry/hassio-addons#23]
Hi,

I've had this wonderful plugin working for a few weeks.  It has been working ok, but I have to restart it regularly.    Here are the log messages that show up when this happens:

```
Unable to connect (Lookup error.).
Async read stalled, exiting!
rtlsdr_demod_write_reg failed with -7
r82xx_write: i2c wr failed=-9 reg=06 len=1
Reattached kernel driver
```

One thing you should know about my setup- I am remotely hosting the USB stick for the RTL on a remote device via usbip.  I have a zwave stick on the same remote device and it seems to be fine, so I have no reason to believe that there is connectivity issues between the two devices (they are both on my local LAN).

Anyone seen this issue?

**Comment by agrieco** [comment]
I realize now after looking at the code, its a case of the rtl_433 executable terminating and this has nothing to do with the plugin.  I did “work around it” by putting an outer loop in the script to re-call the rtl_433 binary a configurable number of times....ugly but until I can investigate the root cause- it works ok.  Changes of me missing an event are small...but less than ideal for sure.

**Comment by slowsauce** [comment]
Hi, im having this exact or close to exact problem. im not quite understanding what did you do to fix it. im thinking of setting up an automation to just restart the addon if the mqtt system for my temperature sensors does not update within the defined update period.

**Comment by stripeyhorse** [comment]
is this in the current code @agrieco , or can someone please share how to automatically restart on crash/error

**Comment by messismore** [comment]
I had the same issue and changed the addon to restart rtl_433 whenever it crashes. Can you try whether my [fork](https://github.com/messismore/hassio-addons) fixes your issue? If so, I'll issue a pull request.

**Comment by ZBiener** [comment]
@messismore : I tried your adding your fork, but it doesn't look like I'm getting restarts. The add-on still stops reading RF signals after a while. I'm a noob: I'm not sure how to confirm/disconfirm that it is actually starting. Help?

**Comment by messismore** [comment]
@ZBiener huh that's strange, I haven't had issues since. But I'm still learning Docker so I wouldn't be surprised if I did something dumb. I'll try to look into it but I don't know when that will be…

**Comment by ZBiener** [comment]
Thanks. I got around things by automating an HA restart of the plugin every few minutes. It's a hack, but works reasonably well. Thanks.

**Comment by grouts112** [comment]
Also having this same issue..  plugin seems to run for a few minutes then stops..  restarting the plugin kicks it back into life. 
How did you automate a plugin restart ?

**Comment by ZBiener** [comment]
This is the gist. The restart won't happen if an MQTT update happened in the last 3 minutes. But it will check this every 5 minutes. 

First, something that catches any MQTT update, in my case it is from a simplisafe sensor:
```
sensor:
  - platform: mqtt
    name: mqtt_general
    state_topic: "homeassistant/sensor/rf/SimpliSafe_Sensor/null"
```

And the the restart procedure:

```
automation:
- alias: reset_rtl_433_addon #it gets stuck
  trigger:
    - platform: time_pattern
      minutes: '/5'
      seconds: 00
  condition:
    condition: template
    value_template: '{{ ((as_timestamp(now()) - as_timestamp(states.sensor.mqtt_general.last_changed) | default(0)) | int) >= 180 }}'
  action:
   # - service: notify.notify
   #   data:
   #     message: "Restarting 433"
    - service: hassio.addon_restart
      data:
        addon: "77a50ada_rtl4332mqtt"
```
